# Generated by Django 4.1.1 on 2023-01-21 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_dayreport"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dayreport",
            name="agenda_for_trial",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="newcostomer", name="remark", field=models.BooleanField(),
        ),
    ]
