# Generated by Django 4.1.1 on 2023-01-21 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_alter_dayreport_agenda_for_trial_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dayreport",
            name="agenda_for_trial",
            field=models.CharField(max_length=100),
        ),
    ]
