# Generated by Django 4.1.1 on 2023-02-13 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_alter_dayreport_agenda_for_trial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dayreport",
            name="agenda_first_visit",
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name="dayreport",
            name="agenda_for_order",
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name="dayreport",
            name="agenda_for_trial",
            field=models.CharField(max_length=500),
        ),
    ]
