# Generated by Django 4.1.1 on 2023-02-13 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_delete_dayreport"),
    ]

    operations = [
        migrations.CreateModel(
            name="DayReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("time", models.TimeField()),
                ("agenda_first_visit", models.BooleanField()),
                ("agenda_for_order", models.BooleanField()),
                ("agenda_for_trial", models.CharField(max_length=500)),
                ("next_plan", models.CharField(max_length=800)),
            ],
        ),
    ]
