# Generated by Django 4.1.1 on 2023-02-13 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0008_dayreport"),
    ]

    operations = [
        migrations.DeleteModel(name="DayReport",),
    ]
