# Generated by Django 4.1.1 on 2023-02-13 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0012_alter_dayreport_agenda_first_visit_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dayreport",
            name="agenda_first_visit",
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name="newcostomer",
            name="remark",
            field=models.BooleanField(null=True),
        ),
    ]
